// react-customer-dashboard/src/App.js
import { useState, useEffect } from 'react';

function App() {
    const [customers, setCustomers] = useState([]);

    useEffect(() => {
        fetch('http://localhost:1234/api/customers')
            .then((resp) => resp.json())
            .then((data) => setCustomers(data.customers));
    }, []);

    const customerListJsx = customers.map((c) => (
        <tr>
            <td>{c.name}</td>
            <td>{c.email}</td>
            <td>{c.phone}</td>
            <td>{c.city}</td>
        </tr>
    ));

    return (
        <>
            <div className='alert alert-primary'>
                <div className='container'>
                    <h1>Customer dashboard</h1>
                </div>
            </div>

            <div className='container'>
                <table className='table table-bordered table-striped'>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>City</th>
                        </tr>
                    </thead>
                    <tbody>{customerListJsx}</tbody>
                </table>
            </div>
        </>
    );
}

export default App;

// angular-customer-dashboard/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  customers: Array<any> = [];

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.http.get('http://localhost:1234/api/customers')
      .subscribe(this.handler)
  }

  handler = {
    next: (data: any) => {
      this.customers = data.customers
    }
  }
}

<div class="alert alert-primary">
  <div class="container">
    <h1>Customer dashboard</h1>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let c of customers">
        <td>{{ c.name }}</td>
        <td>{{ c.email }}</td>
        <td>{{ c.phone }}</td>
        <td>{{ c.city }}</td>
      </tr>
    </tbody>
  </table>
</div>
